version: '3.12'
services:
  web:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - .:/app
      - ./pytest.ini:/app/pytest.ini
    environment:
      - PYTHONPATH=/app

  test:
    build: .
    command: [ "pytest", "tests" ]
    volumes:
      - .:/app
      - ./pytest.ini:/app/pytest.ini
    environment:
      - PYTHONPATH=/app
